#!/bin/bash

# /etc/init.d/dbod_daemon startup script
#
# Created: icoteril 10/01/2013

PIDFILE="/var/run/dbod_daemon/dbod_daemon.pid"
if [ -e "$PIDFILE" ] 
then
    pid=`cat $PIDFILE`
else
    pid=
fi

status(){
    echo "PIDFILE: $pid" 
    pids=`pgrep -u dbod dbod_daemon`
    echo "PID: $pids"
}

start(){
    if [[ -n "$pid" ]] 
    then
        echo "dbod_daemon already running with PID: $pid"
    else
        su - dbod -c "/usr/bin/dbod_daemon --start"
    fi
}

stop(){
    # Attempts to exit gracefully
    su - dbod -c "/usr/bin/dbod_daemon --stop"
    # Cleans
    if [ -e "$PIDFILE" ]; then
        rm $PIDFILE
    fi
    unset pid
    pkill -9 -U dbod dbod_daemon
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)  
        echo $"Usage: $0 {start|stop|status}"
        exit 1
esac
exit 0
