
package ch.cern.dod.ws.egroups;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CraEgroupsWebService", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", wsdlLocation = "classpath:/WEB-INF/wsdl/egroups.wsdl")
public class CraEgroupsWebService_Service
    extends Service
{

    private final static URL CRAEGROUPSWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ch.cern.dod.ws.egroups.CraEgroupsWebService_Service.class.getName());

    static {
        CRAEGROUPSWEBSERVICE_WSDL_LOCATION = ch.cern.dod.ws.egroups.CraEgroupsWebService_Service.class.getResource("/WEB-INF/wsdl/egroups.wsdl");
    }

    public CraEgroupsWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CraEgroupsWebService_Service() {
        super(CRAEGROUPSWEBSERVICE_WSDL_LOCATION, new QName("https://cra-ws.cern.ch/cra-ws/", "CraEgroupsWebService"));
    }

    /**
     * 
     * @return
     *     returns CraEgroupsWebService
     */
    @WebEndpoint(name = "CraEgroupsWebService")
    public CraEgroupsWebService getCraEgroupsWebService() {
        return super.getPort(new QName("https://cra-ws.cern.ch/cra-ws/", "CraEgroupsWebService"), CraEgroupsWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CraEgroupsWebService
     */
    @WebEndpoint(name = "CraEgroupsWebService")
    public CraEgroupsWebService getCraEgroupsWebService(WebServiceFeature... features) {
        return super.getPort(new QName("https://cra-ws.cern.ch/cra-ws/", "CraEgroupsWebService"), CraEgroupsWebService.class, features);
    }

}
