
package ch.cern.dod.ws.egroups;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CraEgroupsWebService", targetNamespace = "https://cra-ws.cern.ch/cra-ws/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CraEgroupsWebService {


    /**
     * Change External Email Address
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.ChangeExternalEmailAddressResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/changeExternalEmailAddress")
    @WebResult(name = "changeExternalEmailAddressResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public ChangeExternalEmailAddressResponse changeExternalEmailAddress(
        @WebParam(name = "changeExternalEmailAddressRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        ChangeExternalEmailAddressRequest parameters);

    /**
     * Find Egroup By ID
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.FindEgroupByIdResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/findEgroupById")
    @WebResult(name = "findEgroupByIdResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public FindEgroupByIdResponse findEgroupById(
        @WebParam(name = "findEgroupByIdRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        FindEgroupByIdRequest parameters);

    /**
     * Find Egroup By Name
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.FindEgroupByNameResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/findEgroupByName")
    @WebResult(name = "findEgroupByNameResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public FindEgroupByNameResponse findEgroupByName(
        @WebParam(name = "findEgroupByNameRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        FindEgroupByNameRequest parameters);

    /**
     * Create or reload an e-group
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.SynchronizeEgroupResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/synchronizeEgroup")
    @WebResult(name = "synchronizeEgroupResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public SynchronizeEgroupResponse synchronizeEgroup(
        @WebParam(name = "synchronizeEgroupRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        SynchronizeEgroupRequest parameters);

    /**
     * Delete an e-group
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.DeleteEgroupResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/deleteEgroup")
    @WebResult(name = "deleteEgroupResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public DeleteEgroupResponse deleteEgroup(
        @WebParam(name = "deleteEgroupRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        DeleteEgroupRequest parameters);

    /**
     * Add members to an e-group
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.AddEgroupMembersResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/addEgroupMembers")
    @WebResult(name = "addEgroupMembersResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public AddEgroupMembersResponse addEgroupMembers(
        @WebParam(name = "addEgroupMembersRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        AddEgroupMembersRequest parameters);

    /**
     * Add email members to an e-group
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.AddEgroupEmailMembersResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/addEgroupEmailMembers")
    @WebResult(name = "addEgroupEmailMembersResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public AddEgroupEmailMembersResponse addEgroupEmailMembers(
        @WebParam(name = "addEgroupEmailMembersRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        AddEgroupEmailMembersRequest parameters);

    /**
     * Remove members from an e-group
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.RemoveEgroupMembersResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/removeEgroupMembers")
    @WebResult(name = "removeEgroupMembersResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public RemoveEgroupMembersResponse removeEgroupMembers(
        @WebParam(name = "removeEgroupMembersRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        RemoveEgroupMembersRequest parameters);

    /**
     * Add email members from an e-group
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.RemoveEgroupEmailMembersResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/removeEgroupEmailMembers")
    @WebResult(name = "removeEgroupEmailMembersResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public RemoveEgroupEmailMembersResponse removeEgroupEmailMembers(
        @WebParam(name = "removeEgroupEmailMembersRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        RemoveEgroupEmailMembersRequest parameters);

    /**
     * Get all egroups an user own or manage
     * 
     * @param parameters
     * @return
     *     returns ch.cern.dod.ws.egroups.GetEgroupsUserOwnOrManageResponse
     */
    @WebMethod(action = "https://cra-ws.cern.ch/cra-ws/CraEgroupsWebService/getEgroupsUserOwnOrManage")
    @WebResult(name = "getEgroupsUserOwnOrManageResponse", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
    public GetEgroupsUserOwnOrManageResponse getEgroupsUserOwnOrManage(
        @WebParam(name = "getEgroupsUserOwnOrManageRequest", targetNamespace = "https://cra-ws.cern.ch/cra-ws/", partName = "parameters")
        GetEgroupsUserOwnOrManageRequest parameters);

}
