
package ch.cern.dbod.ws;

import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DBODWebService", targetNamespace = "https://syscontrol.cern.ch/Dod/", wsdlLocation = "classpath:/ch/cern/dbod/ws/wsdl/dbodwebservices.wsdl")
public class DBODWebService
    extends Service
{

    private final static URL DBODWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ch.cern.dbod.ws.DBODWebService.class.getName());
    
    static {
        DBODWEBSERVICE_WSDL_LOCATION = ch.cern.dbod.ws.DBODWebService.class.getResource("/ch/cern/dbod/ws/wsdl/dbodwebservices.wsdl");
    }

    public DBODWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DBODWebService() {
        super(DBODWEBSERVICE_WSDL_LOCATION, new QName("https://syscontrol.cern.ch/Dod/", "DBODWebService"));
    }

    /**
     * 
     * @return
     *     returns DBODWebServicePortType
     */
    @WebEndpoint(name = "DBODWebServicePort")
    public DBODWebServicePortType getDBODWebServicePort() {
        return super.getPort(new QName("https://syscontrol.cern.ch/Dod/", "DBODWebServicePort"), DBODWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DBODWebServicePortType
     */
    @WebEndpoint(name = "DBODWebServicePort")
    public DBODWebServicePortType getDBODWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("https://syscontrol.cern.ch/Dod/", "DBODWebServicePort"), DBODWebServicePortType.class, features);
    }

}
