#!/bin/bash

# /etc/init.d/dod_daemon startup script
#
# Created: icoteril 10/01/2013


status(){
    if [ -e "/tmp/dod_daemon.pid" ]; then
        pid=`cat /tmp/dod_daemon.pid`
        echo "Expected PID: $pid" 
    fi
    pids=`ps ax|grep "perl -w /usr/bin/dod_daemon" |grep -v grep`
    echo "Found : $pids"
}

start(){
    if [ -e "/tmp/dod_daemon.pid" ]; then
        pid=`cat /tmp/dod_daemon.pid`
        echo "dod_daemon already running with PID: $pid"
    else
        su - dbod -c "/usr/bin/dod_daemon --start"
    fi
}

stop(){
    if [ -e "/tmp/dod_daemon.pid" ]; then
        rm /tmp/dod_daemon.pid
    fi
    pkill -9 dod_daemon
}

case "$1" in
    start)
        stop
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)  
        echo $"Usage: $0 {start|stop|status}"
        exit 1
esac
exit 0
