-- Insert command definitions
INSERT INTO dod_command_definition VALUES ('DISABLE_AUTOMATIC_BACKUPS', 'ALL', NULL, 'DEV');
INSERT INTO dod_command_definition VALUES ('DISABLE_BACKUPS_TO_TAPE', 'ALL', NULL, 'DEV');
INSERT INTO dod_command_definition VALUES ('ENABLE_AUTOMATIC_BACKUPS', 'ALL', NULL, 'DEV');
INSERT INTO dod_command_definition VALUES ('ENABLE_BACKUPS_TO_TAPE', 'ALL', NULL, 'DEV');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'MYSQL', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('BACKUP_TO_TAPE', 'MYSQL', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('BACKUP_LOGS_TO_TAPE', 'MYSQL', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'MYSQL', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'MYSQL', NULL, 'DEV');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'MYSQL', NULL, 'DEV');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'MYSQL', '-to :VERSION_TO=', 'DEV');
INSERT INTO dod_command_definition VALUES ('UPLOAD_CONFIG', 'MYSQL', '-file :CONFIG_FILE=', 'DEV');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'ORACLE', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('CLEANUP', 'ORACLE', '-debug -arch', 'DEV');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'ORACLE', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'ORACLE', '-debug -listener :LISTENER_BOOLEAN=', 'DEV');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'ORACLE', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'ORACLE', '-from :VERSION_FROM= -to :VERSION_TO=', 'DEV');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'ORA', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'ORA', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'ORA', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'ORA', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'ORA', '-from :VERSION_FROM= -to :VERSION_TO=', 'DEV');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'PG', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('BACKUP_TO_TAPE', 'PG', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('BACKUP_LOGS_TO_TAPE', 'PG', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('CLEANUP', 'PG', '-debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'PG', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'DEV');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'PG', NULL, 'DEV');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'PG', NULL, 'DEV');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'PG', '-to :VERSION_TO=', 'DEV');
INSERT INTO dod_command_definition VALUES ('UPLOAD_CONFIG', 'PG', '-file :CONFIG_FILE= -type :CONFIG_TYPE= -reload #RELOAD_CONFIG=', 'DEV');

INSERT INTO dod_command_definition VALUES ('DISABLE_AUTOMATIC_BACKUPS', 'ALL', NULL, 'REF');
INSERT INTO dod_command_definition VALUES ('DISABLE_BACKUPS_TO_TAPE', 'ALL', NULL, 'REF');
INSERT INTO dod_command_definition VALUES ('ENABLE_AUTOMATIC_BACKUPS', 'ALL', NULL, 'REF');
INSERT INTO dod_command_definition VALUES ('ENABLE_BACKUPS_TO_TAPE', 'ALL', NULL, 'REF');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'MYSQL', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('BACKUP_TO_TAPE', 'MYSQL', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('BACKUP_LOGS_TO_TAPE', 'MYSQL', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'MYSQL', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'REF');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'MYSQL', NULL, 'REF');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'MYSQL', NULL, 'REF');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'MYSQL', '-to :VERSION_TO=', 'REF');
INSERT INTO dod_command_definition VALUES ('UPLOAD_CONFIG', 'MYSQL', '-file :CONFIG_FILE=', 'REF');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'ORACLE', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('CLEANUP', 'ORACLE', '-debug -arch', 'REF');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'ORACLE', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'REF');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'ORACLE', '-debug -listener :LISTENER_BOOLEAN=', 'REF');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'ORACLE', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'ORACLE', '-from :VERSION_FROM= -to :VERSION_TO=', 'REF');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'ORA', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'ORA', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'REF');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'ORA', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'ORA', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'ORA', '-from :VERSION_FROM= -to :VERSION_TO=', 'REF');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'PG', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('BACKUP_TO_TAPE', 'PG', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('BACKUP_LOGS_TO_TAPE', 'PG', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('CLEANUP', 'PG', '-debug', 'REF');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'PG', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'REF');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'PG', NULL, 'REF');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'PG', NULL, 'REF');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'PG', '-to :VERSION_TO=', 'REF');
INSERT INTO dod_command_definition VALUES ('UPLOAD_CONFIG', 'PG', '-file :CONFIG_FILE= -type :CONFIG_TYPE= -reload #RELOAD_CONFIG=', 'REF');

INSERT INTO dod_command_definition VALUES ('DISABLE_AUTOMATIC_BACKUPS', 'ALL', NULL, 'PROD');
INSERT INTO dod_command_definition VALUES ('DISABLE_BACKUPS_TO_TAPE', 'ALL', NULL, 'PROD');
INSERT INTO dod_command_definition VALUES ('ENABLE_AUTOMATIC_BACKUPS', 'ALL', NULL, 'PROD');
INSERT INTO dod_command_definition VALUES ('ENABLE_BACKUPS_TO_TAPE', 'ALL', NULL, 'PROD');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'MYSQL', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('BACKUP_TO_TAPE', 'MYSQL', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('BACKUP_LOGS_TO_TAPE', 'MYSQL', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'MYSQL', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'MYSQL', NULL, 'PROD');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'MYSQL', NULL, 'PROD');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'MYSQL', '-to :VERSION_TO=', 'PROD');
INSERT INTO dod_command_definition VALUES ('UPLOAD_CONFIG', 'MYSQL', '-file :CONFIG_FILE=', 'PROD');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'ORACLE', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('CLEANUP', 'ORACLE', '-debug -arch', 'PROD');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'ORACLE', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'ORACLE', '-debug -listener :LISTENER_BOOLEAN=', 'PROD');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'ORACLE', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'ORACLE', '-from :VERSION_FROM= -to :VERSION_TO=', 'PROD');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'ORA', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'ORA', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'ORA', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'ORA', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'ORA', '-from :VERSION_FROM= -to :VERSION_TO=', 'PROD');
INSERT INTO dod_command_definition VALUES ('BACKUP', 'PG', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('BACKUP_TO_TAPE', 'PG', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('BACKUP_LOGS_TO_TAPE', 'PG', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('CLEANUP', 'PG', '-debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('RESTORE', 'PG', '-r :SNAPSHOT= -t #TIMESTAMP= -debug', 'PROD');
INSERT INTO dod_command_definition VALUES ('SHUTDOWN', 'PG', NULL, 'PROD');
INSERT INTO dod_command_definition VALUES ('STARTUP', 'PG', NULL, 'PROD');
INSERT INTO dod_command_definition VALUES ('UPGRADE', 'PG', '-to :VERSION_TO=', 'PROD');
INSERT INTO dod_command_definition VALUES ('UPLOAD_CONFIG', 'PG', '-file :CONFIG_FILE= -type :CONFIG_TYPE= -reload #RELOAD_CONFIG=', 'PROD');
