-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665
--   at:        2011-10-13 10:39:27 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE dod_command_definition 
    ( 
     command_name VARCHAR2 (64)  NOT NULL , 
     type VARCHAR2 (64)  NOT NULL , 
     exec VARCHAR2 (2048)  NOT NULL 
    ) 
;



ALTER TABLE dod_command_definition 
    ADD CONSTRAINT pk_dod_command_definition PRIMARY KEY ( command_name, type ) ;


CREATE TABLE dod_command_params 
    ( 
     username VARCHAR2 (32)  NOT NULL , 
     db_name VARCHAR2 (128)  NOT NULL , 
     command_name VARCHAR2 (64)  NOT NULL , 
     type VARCHAR2 (64)  NOT NULL , 
     creation_date DATE  NOT NULL , 
     name VARCHAR2 (64)  NOT NULL , 
     value CLOB 
    ) 
;



ALTER TABLE dod_command_params 
    ADD CONSTRAINT pk_dod_command_params PRIMARY KEY ( username, db_name, command_name, type, creation_date, name ) ;


CREATE TABLE dod_instances 
    ( 
     username VARCHAR2 (32)  NOT NULL , 
     db_name VARCHAR2 (128)  NOT NULL , 
     e_group VARCHAR2 (256) , 
     category VARCHAR2 (32)  NOT NULL , 
     creation_date DATE  NOT NULL , 
     expiry_date DATE , 
     db_type VARCHAR2 (32)  NOT NULL , 
     db_size INTEGER  NOT NULL , 
     no_connections INTEGER , 
     project VARCHAR2 (128) , 
     description VARCHAR2 (1024) , 
     state VARCHAR2 (32) , 
     status CHAR (1) 
    ) 
;



ALTER TABLE dod_instances 
    ADD CONSTRAINT pk_dod_instances PRIMARY KEY ( username, db_name ) ;

ALTER TABLE dod_instances 
    ADD CONSTRAINT unique_db_name UNIQUE ( db_name ) ;


CREATE TABLE dod_jobs 
    ( 
     username VARCHAR2 (32)  NOT NULL , 
     db_name VARCHAR2 (128)  NOT NULL , 
     command_name VARCHAR2 (64)  NOT NULL , 
     type VARCHAR2 (64)  NOT NULL , 
     creation_date DATE  NOT NULL , 
     completion_date DATE , 
     requester VARCHAR2 (32)  NOT NULL , 
     admin_action INTEGER  NOT NULL , 
     state VARCHAR2 (32)  NOT NULL , 
     log CLOB , 
     result VARCHAR2 (2048) 
    ) 
;



ALTER TABLE dod_jobs 
    ADD CONSTRAINT pk_dod_jobs PRIMARY KEY ( username, db_name, command_name, type, creation_date ) ;



ALTER TABLE dod_jobs 
    ADD CONSTRAINT dod_jobs_definitions FOREIGN KEY 
    ( 
     command_name,
     type
    ) 
    REFERENCES dod_command_definition 
    ( 
     command_name,
     type
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE dod_jobs 
    ADD CONSTRAINT dod_jobs_instances FOREIGN KEY 
    ( 
     username,
     db_name
    ) 
    REFERENCES dod_instances 
    ( 
     username,
     db_name
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE dod_command_params 
    ADD CONSTRAINT dod_params_jobs FOREIGN KEY 
    ( 
     username,
     db_name,
     command_name,
     type,
     creation_date
    ) 
    REFERENCES dod_jobs 
    ( 
     username,
     db_name,
     command_name,
     type,
     creation_date
    ) 
    ON DELETE CASCADE 
;







-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

