/*
 * Copyright (C) 2015, CERN
 * This software is distributed under the terms of the GNU General Public
 * Licence version 3 (GPL Version 3), copied verbatim in the file "LICENSE".
 * In applying this license, CERN does not waive the privileges and immunities
 * granted to it by virtue of its status as Intergovernmental Organization
 * or submit itself to any jurisdiction.
 */

package ch.cern.dbod.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DBODWebServicePortType", targetNamespace = "https://syscontrol.cern.ch/Dod/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DBODWebServicePortType {


    /**
     * 
     * @param instance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSnapshots", action = "https://syscontrol.cern.ch/Dod/#GetSnapshots")
    @WebResult(name = "snapshots", partName = "snapshots")
    public String getSnapshots(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOraSnapshots", action = "https://syscontrol.cern.ch/Dod/#GetOraSnapshots")
    @WebResult(name = "snapshots", partName = "snapshots")
    public String getOraSnapshots(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSlowLogs", action = "https://syscontrol.cern.ch/Dod/#GetSlowLogs")
    @WebResult(name = "slowLogs", partName = "slowLogs")
    public String getSlowLogs(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOracleLogs", action = "https://syscontrol.cern.ch/Dod/#GetOracleLogs")
    @WebResult(name = "logs", partName = "logs")
    public String getOracleLogs(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOraLogs", action = "https://syscontrol.cern.ch/Dod/#GetOraLogs")
    @WebResult(name = "logs", partName = "logs")
    public String getOraLogs(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPGLogs", action = "https://syscontrol.cern.ch/Dod/#GetPGLogs")
    @WebResult(name = "logs", partName = "logs")
    public String getPGLogs(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMySQLConfigFile", action = "https://syscontrol.cern.ch/Dod/#GetMySQLConfigFile")
    @WebResult(name = "file", partName = "file")
    public String getMySQLConfigFile(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPGConfigFile", action = "https://syscontrol.cern.ch/Dod/#GetPGConfigFile")
    @WebResult(name = "file", partName = "file")
    public String getPGConfigFile(
        @WebParam(name = "instance", partName = "instance")
        String instance,
        @WebParam(name = "type", partName = "type")
        String type);

    /**
     * 
     * @param instance
     * @param filePath
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ServeFile", action = "https://syscontrol.cern.ch/Dod/#ServeFile")
    @WebResult(name = "url", partName = "url")
    public String serveFile(
        @WebParam(name = "instance", partName = "instance")
        String instance,
        @WebParam(name = "filePath", partName = "filePath")
        String filePath);

    /**
     * 
     * @param instance
     * @param param
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParam", action = "https://syscontrol.cern.ch/Dod/#GetParam")
    @WebResult(name = "paramValue", partName = "paramValue")
    public String getParam(
        @WebParam(name = "instance", partName = "instance")
        String instance,
        @WebParam(name = "param", partName = "param")
        String param);

    /**
     * 
     * @param instance
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetHost", action = "https://syscontrol.cern.ch/Dod/#GetHost")
    @WebResult(name = "host", partName = "host")
    public String getHost(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CheckMYSQLAppDynamics", action = "https://syscontrol.cern.ch/Dod/#CheckMYSQLAppDynamics")
    @WebResult(name = "status", partName = "status")
    public Integer checkMYSQLAppDynamics(
        @WebParam(name = "instance", partName = "instance")
        String instance);

    /**
     * 
     * @param instance
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CheckPGAppDynamics", action = "https://syscontrol.cern.ch/Dod/#CheckPGAppDynamics")
    @WebResult(name = "status", partName = "status")
    public Integer checkPGAppDynamics(
        @WebParam(name = "instance", partName = "instance")
        String instance);

}
